### ISSUE TITLE
Compile failed on tun

### ISSUE THREAD

**Issue by dterweij** [mlangelaar/jnos2#2]
Hi,

System Ubuntu

`gcc -DUNIX -g3   -DDEBUG -Wall   -c -o tun.o tun.c
In file included from netuser.h:38:0,
                 from tcp.h:26,
                 from iface.h:25,
                 from tun.c:26:
socket.h:85:21: error: expected identifier before numeric constant
 #define SOCK_STREAM 0
                     ^
In file included from /usr/include/i386-linux-gnu/sys/socket.h:33:0,
                 from /usr/include/linux/if.h:28,
                 from tun.c:41:
/usr/include/i386-linux-gnu/bits/socket.h:175:8: error: redefinition of ‘struct sockaddr’
 struct sockaddr
        ^~~~~~~~
In file included from socket.h:22:0,
                 from netuser.h:38,
                 from tcp.h:26,
                 from iface.h:25,
                 from tun.c:26:
sockaddr.h:13:8: note: originally defined here
 struct sockaddr {
        ^~~~~~~~
<builtin>: recipe for target 'tun.o' failed
make: *** [tun.o] Error 1
`

**Comment by mlangelaar** [comment]
Good day, sorry about that folks, here is some info :

  For those trying to compile JNOS 2.0k.1 on debian-stretch-DI-rc4-i386

  Replace existing tun.c with one from link below (kludge fix for now), 
then 'make'

https://www.langelaar.net/jnos2/Archive23Jan2019/archive/news/tun_sp2l.c

It's not just for debian-stretch-.....

With kind regards,

Maiko

**Comment by mlangelaar** [comment]
This has been long resolved, no more patch required, it's just fixed now.
