### ISSUE TITLE
jnosinstaller not working

### ISSUE THREAD

**Issue by MichTronics** [mlangelaar/jnos2#4]
The jnosinstaller i don't get it to work in this version, the 2.0m version true rsync is working.

**Comment by mlangelaar** [comment]
sorry for the delayed response Mich, that installer was written a long time ago, to give folks a basic starting configuration, if any, the biggest issue is that one needs to recompile it from source, as well, one definitely has to replace the JNOS binary that comes with it with something more recent. One of these days I may work on it again, sorry, but thanks for the report. Maiko / VE4KLM
